/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_Removed_Quote_line_ItemTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_Removed_Quote_line_ItemTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new Removed_Quote_line_Item__c());
    }
}