@isTest
public class MarketoLeadGenerationWebserviceTest {
   @isTest
    public static void runPositiveTest(){
    MarketoLeadGenerationWebservice deprecated = new MarketoLeadGenerationWebservice ();

      /*  RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestUri = '/services/apexrest/createlead';
        req.httpMethod = 'GET';
        req.addParameter('firstname', 'ftest');
        req.addParameter('lastname', 'ltest');
        req.addParameter('email', 'test@test.com');
        req.addParameter('company', 'ABC');
        req.addParameter('jobtitle', 'Janitor');
        req.addParameter('state', 'WI');
        req.addParameter('country', 'United States');
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        MarketoLeadGenerationWebservice.doGet();
        Test.stopTest(); */
    }
   /*
    @isTest
    public static void runNegativeTest(){
       RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestUri = '/services/apexrest/createlead';
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        MarketoLeadGenerationWebservice.doGet();
        Test.stopTest();
    } */
}